### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by ttyfly** [Sepecter/First-Python-program#1]
写得不错，但还存在一个小问题：

排序指的是将 data 中的数据进行排序，order 存储的是排序标准。比如按标题进行字典序排序，那么 order 就存 "title"。也就是说，你需要编写程序，对 data 中的内容进行排序，然后将排序标准存进 order。然后最好可以通过控制台控制排序标准。

（你选用的网站似乎重新排序意义不大233，不过还是写一下排序功能吧，因为这是一项考察内容）

修改完后，可以直接在此 issue 下发表回复，我会再次查看。

**Comment by Sepecter** [comment]
> 写得不错，但还存在一个小问题：
> 
> 排序指的是将 data 中的数据进行排序，order 存储的是排序标准。比如按标题进行字典序排序，那么 order 就存 "title"。也就是说，你需要编写程序，对 data 中的内容进行排序，然后将排序标准存进 order。然后最好可以通过控制台控制排序标准。
> 
> （你选用的网站似乎重新排序意义不大233，不过还是写一下排序功能吧，因为这是一项考察内容）
> 
> 修改完后，可以直接在此 issue 下发表回复，我会再次查看。

带排序的2.0版已经上传到仓库中了，排序标准在代码中有写到

**Comment by ttyfly** [comment]
> 
> 
> > 写得不错，但还存在一个小问题：
> > 排序指的是将 data 中的数据进行排序，order 存储的是排序标准。比如按标题进行字典序排序，那么 order 就存 "title"。也就是说，你需要编写程序，对 data 中的内容进行排序，然后将排序标准存进 order。然后最好可以通过控制台控制排序标准。
> > （你选用的网站似乎重新排序意义不大233，不过还是写一下排序功能吧，因为这是一项考察内容）
> > 修改完后，可以直接在此 issue 下发表回复，我会再次查看。
> 
> 带排序的2.0版已经上传到仓库中了，排序标准在代码中有写到

已查看，完成度很高。感谢您的参与。后续会公布参考代码和夏令营优秀营员名单，敬请关注。
